interface WordsDictionary {
	[key: string]: {
		display: string,
		description: string;
		words: string;
	};
}

export const wordsDictionary: WordsDictionary = {
	"blank": { display: "Blank", description: "Right middle", words: "Wait, Right, Okay, Middle, Blank" },
	"done": { display: "Done", description: "", words: "Sure, U-H H-U-H, Next, What?, Y-O-U-R, U-R, Y-O-U'R-E, Hold, Like, Y-O-U, U, You are, U-H U-H, done" },
	"first": { display: "First", description: "Right top", words: "Left, Okay, Yes, Middle, No, Right, Nothing, U-H-H-H, Wait, Ready, Blank, What, Press, First" },
	"hold": { display: "Hold", description: "", words: "You Are, U, Done, U-H U-H, Y-O-U, U-R, Sure, What?, Y-O-U'R-E, Next, Hold" },
	"left": { display: "Left", description: "", words: "Right, left" },
	"like": { display: "Like", description: "", words: "Y-O-U'R-E, Next, U, U-R, Hold, Done, U-H U-H, What?, U-H H-U-H, Y-O-U, Like" },
	"middle": { display: "Middle", description: "", words: "Blank, Ready, Okay, What, Nothing, Press, No, Wait, Left, Middle" },
	"next": { display: "Next", description: "", words: "What?, U-H H-U-H, U-H U-H, Y-O-U-R, Hold, Sure, Next" },
	"no": { display: "No", description: "Right bottom", words: "Blank, U-H-H-H, Wait, First, What, Ready, Right, Yes, Nothing, Left, Press, Okay, No" },
	"nothing": { display: "Nothing", description: "Left middle", words: "U-H-H-H, Right, Okay, Middle, Yes, Blank, No, Press, Left, What, Wait, First, Nothing" },
	"okay": { display: "Okay", description: "Right top", words: "Middle, No, First, Yes, U-H-H-H, Nothing, Wait, Okay" },
	"press": { display: "Press", description: "", words: "Right, Middle, Yes, Ready, Press" },
	"ready": { display: "Ready", description: "", words: "Yes, Okay, What, Middle, Left, Press, Right, Blank, Ready" },
	"right": { display: "Right", description: "", words: "Yes, Nothing, Ready, Press, No, Wait, What, Right" },
	"sure": { display: "Sure", description: "", words: "You Are, Done, Like, Y-O-U'R-E, Y-O-U, Hold, U-H H-U-H, U-R, Sure" },
	"u": { display: "U", description: "", words: "U-H H-U-H, Sure, Next, What?, Y-O-U'R-E, U-R, U-H U-H, Done, U" },
	"uhhuh": { display: "Uh huh", description: "", words: "U-H H-U-H" },
	"uhuh": { display: "Uh Uh", description: "", words: "U-R, U, You Are, Y-O-U'R-E, Next, U-H U-H" },
	"uhhh": { display: "Uhhh", description: "", words: "Ready, Nothing, Left, What, Okay, Yes, Right, No, Press, Blank, U-H-H-H" },
	"ur": { display: "Ur", description: "Left top", words: "Done, U, U-R" },
	"wait": { display: "Wait", description: "", words: "U-H-H-H, No, Blank, Okay, Yes, Left, First, Press, What, Wait" },
	"what": { display: "What", description: "", words: "U-H-H-H, What" },
	"whatq": { display: "What?", description: "", words: "Y-O-U, Hold, Y-O-U'R-E, Y-O-U-R, U, Doe, U-H U-H, Like, You Are, U-H H-U-H, U-R, Next, What?" },
	"yes": { display: "Yes", description: "Left middle", words: "Okay, Right, U-H-H-H, Middle, First, What, Press, Ready, Nothing, Yes" },
	"youare": { display: "You Are", description: "Right bottom", words: "Y-O-U-R, Next, Like, U-H H-U-H, What?, Done, U-H U-H, Hold, Y-O-U, U, Y-O-U'R-E, Sure, U-R, You Are" },
	"you": { display: "You", description: "Right middle", words: "Sure, You Are, Y-O-U-R, Y-O-U-'R-E, Next, U-H H-U-H, U-R, Hold, What?, Y-O-U" },
	"your": { display: "Your", description: "Right middle", words: "U-H U-H, You Are, U-H H-U-H, Y-O-U-R" },
	"youre": { display: "You're", description: "Right middle", words: "Y-O-U, Y-O-U'R-E" },
	"c": { display: "C", description: "Right top", words: "" },
	"cee": { display: "Cee", description: "Right bottom", words: "" },
	"display": { display: "Display", description: "Right bottom", words: "" },
	"holdon": { display: "Hold On", description: "Right bottom", words: "" },
	"lead": { display: "Lead", description: "Right bottom", words: "" },
	"led": { display: "Led", description: "Left middle", words: "" },
	"leed": { display: "Leed", description: "Left bottom", words: "" },
	"read": { display: "Read", description: "Right middle", words: "" },
	"red": { display: "Red", description: "Right middle", words: "" },
	"reed": { display: "Reed", description: "Left bottom", words: "" },
	"says": { display: "Says", description: "Right Bottom", words: "" },
	"see": { display: "See", description: "Right bottom", words: "" },
	"their": { display: "Their", description: "Right middle", words: "" },
	"there": { display: "There", description: "Right bottom", words: "" },
	"theyare": { display: "They Are", description: "Left middle", words: "" },
	"theyre": { display: "They're", description: "Left bottom", words: "" },
	"space": { display: " ", description: "Left bottom", words: "" }
};