# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: '*'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  quality:
    name: Tests
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Run something
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: echo Fuuuuuuuuken eh bud.
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run testci
    
    
    

